export const BACKOFFICE_SERVICE = 'BACKOFFICE_SERVICE';
export const CHALLENGES_SERVICE = 'CHALLENGES_SERVICE';
export const RANKINGS_SERVICE = 'RANKINGS_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';
